/**
 * @GUARD('MEMBER') =>
 *    @CACHE([TEAM_MEMBER.ID]: ROLE) :: CLEAR CACHE ON ANY TEAM_MEMBER.ID UPDATE
 *
 *    GET_TEAM_MEMBER.REPOSITORY HAS ROLE
 *       ? REQUEST.TEAM_MEMBER = TEAM_MEMBER
 *       : THROW BAD_REQUEST()
 *
 * Controller() => {
 *    SECTION [GET_ENTITY_USE_CASE]
 *
 *    IF (!TEAM_MEMBER.TEAM_ID.EQUALS(ENTITY.TEAM_ID)) {
 *       THROW BAD_REQUEST()
 *    }
 *
 *    SECTION [USE_CASE]
 * }
 */
